# Generated by Django 5.2.17 on 2026-09-05 15:37

import apps.recipes.models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION normalize_ru(text) RETURNS text AS $$
  SELECT lower(translate($1, 'Ёё', 'Ее'));
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;
""",
            reverse_sql="DROP FUNCTION IF EXISTS normalize_ru(text);",
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.SlugField(max_length=80, unique=True)),
                ('title', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('density_g_per_ml', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('allergens_contains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('allergens_may_contain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('allergens_unknown', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.TextField()),
                ('protein_base', models.CharField(choices=[('beef', 'beef'), ('eggs_dairy', 'eggs_dairy'), ('fish_red_sea', 'fish_red_sea'), ('fish_river', 'fish_river'), ('fish_white_sea', 'fish_white_sea'), ('lamb', 'lamb'), ('legumes', 'legumes'), ('mushrooms', 'mushrooms'), ('offal', 'offal'), ('pork', 'pork'), ('poultry', 'poultry'), ('seafood', 'seafood'), ('vegetables', 'vegetables'), ('vegetarian', 'vegetarian')], max_length=32)),
                ('cook_method', models.CharField(choices=[('air_fryer', 'air_fryer'), ('boil', 'boil'), ('deep_fry', 'deep_fry'), ('grill', 'grill'), ('no_cook', 'no_cook'), ('oven', 'oven'), ('pan_fry', 'pan_fry'), ('steam', 'steam'), ('stew', 'stew')], max_length=32)),
                ('dish_type', models.CharField(choices=[('appetizer', 'appetizer'), ('bakery', 'bakery'), ('breakfast', 'breakfast'), ('dessert', 'dessert'), ('drink', 'drink'), ('main', 'main'), ('pasta_grains', 'pasta_grains'), ('preserve', 'preserve'), ('salad', 'salad'), ('sauce', 'sauce'), ('side', 'side'), ('soup', 'soup')], max_length=32)),
                ('scale_mode', models.CharField(choices=[('gentle', 'gentle'), ('linear', 'linear'), ('manual', 'manual'), ('whole', 'whole')], default='linear', max_length=16)),
                ('scalable', models.BooleanField(default=True)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source_name', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_type', models.TextField(blank=True, null=True)),
                ('editorial_tested', models.BooleanField(default=False)),
                ('high_risk_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('child_food', 'child_food'), ('fermentation', 'fermentation'), ('fire_hazard', 'fire_hazard'), ('ground_meat', 'ground_meat'), ('poultry_temp', 'poultry_temp'), ('preservation', 'preservation'), ('raw_egg', 'raw_egg'), ('raw_fish', 'raw_fish'), ('raw_meat', 'raw_meat'), ('raw_milk', 'raw_milk'), ('wild_mushrooms', 'wild_mushrooms')], max_length=32), blank=True, default=list, size=None)),
                ('caution_text', models.TextField(blank=True, null=True)),
                ('energy_profile', models.CharField(choices=[('light', 'light'), ('rich', 'rich'), ('standard', 'standard')], default='standard', max_length=16)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('draft', 'draft'), ('in_review', 'in_review'), ('published', 'published')], default='published', max_length=16)),
                ('ingredient_titles', models.TextField(blank=True, default='')),
                ('variations', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=apps.recipes.models.ToTsVector('russian', apps.recipes.models.NormalizeRu(django.db.models.functions.text.Concat(models.F('title'), models.Value(' ', output_field=models.TextField()), models.F('ingredient_titles'), models.Value(' ', output_field=models.TextField()), django.db.models.functions.comparison.Coalesce(models.F('summary'), models.Value('', output_field=models.TextField())), output_field=models.TextField()))), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='recipes_rec_search__ce256b_gin'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(apps.recipes.models.NormalizeRu('title'), name='gin_trgm_ops'), name='recipe_title_trgm')],
            },
        ),
        migrations.CreateModel(
            name='RecipeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_json', models.JSONField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('draft', 'draft'), ('in_review', 'in_review'), ('published', 'published')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('timer_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('timer_label', models.TextField(blank=True, null=True)),
                ('timer_note', models.TextField(blank=True, null=True)),
                ('pull_internal_temperature_c', models.PositiveIntegerField(blank=True, null=True)),
                ('target_internal_temperature_c', models.PositiveIntegerField(blank=True, null=True)),
                ('hold_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('equipment_note', models.TextField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(choices=[('bunch', 'bunch'), ('clove', 'clove'), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('pcs', 'pcs'), ('pinch', 'pinch'), ('slice', 'slice'), ('tbsp', 'tbsp'), ('to_taste', 'to_taste'), ('tsp', 'tsp')], max_length=16)),
                ('detail', models.TextField(blank=True, null=True)),
                ('scale_mode', models.CharField(choices=[('gentle', 'gentle'), ('linear', 'linear'), ('manual', 'manual'), ('whole', 'whole')], default='linear', max_length=16)),
                ('scalable', models.BooleanField(default=True)),
                ('is_anchor', models.BooleanField(default=False)),
                ('choice_group', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_anchor', True)), fields=('recipe',), name='recipes_one_anchor_per_recipe')],
            },
        ),
    ]
