# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_protein_base_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="axis_snapshots",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
