# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_axis_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="content_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="recipe",
            name="snapshot_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="snapshots_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
