# Generated by Django 5.2

import hashlib
import json

from django.db import migrations, models


def assign_revision_numbers(apps, schema_editor):
    RecipeRevision = apps.get_model("recipes", "RecipeRevision")
    grouped: dict[int, list] = {}
    for row in RecipeRevision.objects.order_by("recipe_id", "created_at", "id"):
        grouped.setdefault(row.recipe_id, []).append(row)
    for rows in grouped.values():
        for index, row in enumerate(rows, start=1):
            encoded = json.dumps(
                row.payload_json, sort_keys=True, default=str, ensure_ascii=False
            )
            row.number = index
            row.payload_hash = hashlib.sha256(encoded.encode("utf-8")).hexdigest()
            row.save(update_fields=["number", "payload_hash"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_recipe_content_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperevision",
            name="number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reciperevision",
            name="payload_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(assign_revision_numbers, noop),
        migrations.AlterField(
            model_name="reciperevision",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("servings__isnull", True))
                | models.Q(("servings__gte", 1)),
                name="recipe_servings_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("yield_weight_g__isnull", True))
                | models.Q(("yield_weight_g__gt", 0)),
                name="recipe_yield_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("time_total_minutes__isnull", True))
                | models.Q(("time_total_minutes__gte", 1)),
                name="recipe_total_time_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("time_active_minutes__isnull", True))
                | models.Q(("time_active_minutes__gte", 0)),
                name="recipe_active_time_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("time_total_minutes__isnull", True))
                | models.Q(("time_active_minutes__isnull", True))
                | models.Q(("time_active_minutes__lte", models.F("time_total_minutes"))),
                name="recipe_active_time_not_greater_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "position"),
                name="recipe_ingredient_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__isnull", True)) | models.Q(("amount__gte", 0)),
                name="recipe_ingredient_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_max__isnull", True))
                | models.Q(("amount_max__gte", 0)),
                name="recipe_ingredient_amount_max_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipestep",
            constraint=models.UniqueConstraint(
                fields=("recipe", "position"),
                name="recipe_step_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="reciperevision",
            constraint=models.UniqueConstraint(
                fields=("recipe", "number"),
                name="recipe_revision_number_unique",
            ),
        ),
    ]
