# Generated by Django 5.2

from django.db import migrations
from django.db.models import F


def backfill_snapshot_version(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    Recipe.objects.exclude(axis_snapshots=[]).filter(snapshot_version=0).update(
        snapshot_version=F("content_version")
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_recipe_constraints_and_revision_number"),
    ]

    operations = [
        migrations.RunPython(backfill_snapshot_version, noop),
    ]
