# Generated by Django 5.2.17 on 2026-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('guide', 'guide'), ('meat', 'meat')], max_length=16)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.TextField()),
                ('payload_json', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'slug'), name='content_document_type_slug_uniq')],
            },
        ),
    ]
